---
title: "Chapter 2"
format: html
editor: visual
---

# **Workflow: Data transformation**

```{r}
library(tidyverse)
library(nycflights13)
names(flights)
flights |>
  filter(dep_delay > 120)

flights |>
  filter(month == 1 | month == 2)

flights |>
  filter(month %in% c(1,2))

flights |>
  arrange(year, month, day, desc(dep_time)) #THE desc makes the dep_time start with the largest shows the order in descinding order. arranging the data.

flights |>
  distinct(dest, origin, .keep_all = TRUE) #the .keep_all = TRUE will make the graph include all the other columns.Distinct find the first occurence of the condition and disregard the rest

flights |> 
  count(origin, dest, sort = TRUE) #with the sort = TRUE i arrange them in descending order of the number of occurences. highest first. 
```

## EXERCISES 

```{r}
# task 1
library(tidyverse)
library(nycflights13)
names(flights)

flights |> 
  filter(arr_time >= 2) |> 
  filter(dest %in% c("IAH","HOU")) |> 
  filter(carrier  %in% c("UA", "AA" ,"DL")) |> 
  filter(month %in% c(7:9)) |> 
  filter(arr_delay > 2 & dep_delay == 0) # i know the task want them all toghether, but the learning outcome is greater for this one. 

flights |> 
  arrange(desc(dep_delay), dep_time) #here the code arrange by the first variable fist. when there is a tie, the second variable kicks inn, and its then arrange wtr to the second variable for the equal values.

flights |> 
  arrange(desc(distance/air_time)) #here the distance / air times makes most sense since i want to see the realtionship between the distance and how much time is spent in the air. 

flights |> 
  distinct(year,month,day) |> 
  nrow() #here distinct finds the first occurence of condition and skipps the rest. so here it looks for all the first occurences of year,month,day and if there is missing of some comnbinations, its not included, then count rows looks at all the rows, and 365 means that there are flights every day. 

flights |> 
  arrange(distance) |> 
  select(carrier, flight, origin, dest, distance)
```

## Columns 

```{r}
flights |> 
  mutate(
    gain = dep_delay - arr_delay,
    speed = distance / air_time * 60,
    .before = 1
  ) #HERE THE .before = 1 means that the new columns are placed first. 
#can also use .after and write the column one wants the new column to be
# Can also use .keep and this will make all the variables used in the mutations be in the graph. 

#the select variable. selects columns by name or intervals.
flights |> 
  select(year, month, day) #can use year:day to make a column including interval. Can use ! to select all the columns, except the ones written.
#some other useful variables: 
#contains, starts_with, end_with and num_range

flights |> 
  relocate(time_hour, air_time)
#relocate moves variables to the front. can use .before and .after


```

### Exercises 

```{r}
#task 1
#the relationship is dep_delay = dep_time − sched_dep_time. the problem here is that the values are written in numbers and not in actually time, meaning when the delay is between hours the minus part will add 40 minutes extra. one needs to convert the numbers into time and then subtract. Another problem is that flights after midnight will not work.

#task 2
#ways to select  dep_time, dep_delay, arr_time, and arr_delay from flights.

#name each column or name them by strings. names that starts with dep or arr. can select them by column position. 

#task 3
#What happens if you specify the name of the same variable multiple times in a select() call? Its unnecassary since they have already been selected, and only adds more computing. 

#task 4
#It selects whichever of those columns exist and silently skips any that don't. so can make a variable that is the vector and then write select(any.of(variable)) and then be able to use the vector easier every time.

#task 5
#here using janitor::clean_names() makes every way to write time included. it is not neccessary since select already includes ignoring the cases when searching for the names. select() ignore upper and lower case by default. this is true when writing select(contains("something"))

#task 6
#Rename air_time to air_time_min to indicate units of measurement and move it to the beginning of the data frame.
# flights |> 
#   rename(air_time_min = air_time) |> 
#   relocate(air_time_min)
# or
# flights |> 
#   mutate(air_time_min = air_time, .before = 1) |> 
#   select(-air_time)

#task 7
#this comes from select and now the function only looks at tailnum, so arr delay is not included

```

## Groups 3.5

```{r}
#group_by() divide the dataset into designed groups
#dosent change the data, but the table says the rows now are grouped by a variable
flights |> 
  group_by(month,year,day)

#summarize()
#reduces the data to have a single row for each group. often useful after a group_by function. 
flights |> 
  group_by(month) |> 
  summarise(avg_delay = mean(dep_delay, na.rm = TRUE),
            n = n()  #this counts all the rows that are in summarized.
  )
#here the na.rm is important for when summarizing there cant by any NA values or else the summerized value is computed with NA and this makes the summarized value also NA. 

#the slice function
#there are 5 different slice functions:
#slice_head(n=1) takes the first row from each group
#slice_tail(n=1) takes the last row from each group
#slice_min(n=1) takes the row with the smallest value of column x
#slice_max(n=1) takes the row with the largest value of column x
#slice_sample(n=1) take a random row
#can also use prop = 0.something to take percentages


#grouping by multiple variables 
#this will group the rows by the variables inserted
#there is also a function called ungroup() which removes the grouping

#.by group by a single argument. A substitute for group_by. if i want to .by multiple variables i need to make a vector c(x,y)

```

### **3.5.7 Exercises**

```{r}
#task 1
flights |> 
  group_by(carrier,dest) |> 
  summarise(average_delay = mean(arr_delay, na.rm = TRUE),
            n = n()) |> 
  arrange(desc(average_delay)) #this code takes the groups with the same carrer and dest, and further show the average delay of the groups in descending order. shows bad airports
flights |>
  group_by(carrier, dest) |>
  summarize(n = n()) #this shows how many rows the carrier are in that flies to specific airports. further showing we cant seperate the effects if the airports or the companies are the reason for arrival delays

#task 2
# Find the flights that are most delayed upon departure to each destination.

flights |> 
  group_by(dest) |>
  slice_max(dep_delay, n = 1) |> 
  relocate(dest, dep_delay)

#task 3
flights|> 
  group_by(hour) |> 
  summarise(avg_dep_delay = mean(dep_delay, na.rm = TRUE),
            n = n()) |> 
  ggplot(aes(hour,avg_dep_delay)) + 
  geom_line() + geom_point() +
  labs(
    title = "average delays over the day",
    y = "average delay",
    x = "when the planes should leave"
  ) 

#task 4
#What happens if you supply a negative n to slice_min() and friends?
#here the everything but kicks in. will show all the rows except the ones defined in the function. 

#task 5
#Explain what count() does in terms of the dplyr verbs you just learned. What does the sort argument to count() do?
#count show how many rows there is that is the columns inside. sort makes the counting happen in a specific order. 








  
```

```{r}
df <- tibble(
  x = 1:5,
  y = c("a", "b", "a", "a", "b"),
  z = c("K", "K", "L", "L", "K")
)
df |>
  group_by(y,z) |>
  summarize(mean_x = mean(x), .groups = "drop")
```
